Copy in monitoring tools from toolbox
ONSdigital/census-rm-monitoring pull request #1
Opened 2020-07-30 12:38 UTC by AdamHawtin

This repo is being split out of [census-rm-toolbox](https://github.com/ONSdigital/census-rm-toolbox/), this PR aims to copy in the monitoring tools from the toolbox as they are.

https://trello.com/c/XHfzQUze/1257-split-cloudshell-utilities-and-monitoring-tools-out-of-census-rm-toolbox

2020-07-30 13:07 UTC, NickGrantONS commented on config.py
> +    EXCEPTIONMANAGER_URL = f'http://{EXCEPTIONMANAGER_HOST}:{EXCEPTIONMANAGER_PORT}'
don't need exception manager?

2020-07-30 13:07 UTC, NickGrantONS commented on config.py
> +    QID_FACTOR = os.getenv('QID_FACTOR', '1')
don't need these

2020-07-30 13:07 UTC, NickGrantONS commented on config.py
> +    BULK_WORKING_DIRECTORY = Path(os.getenv('BULK_WORKING_DIRECTORY', '/tmp'))
don't need this

2020-07-30 13:08 UTC, NickGrantONS commented on config.py
> +    ACTION_PLAN_ID = os.getenv('ACTION_PLAN_ID', '88960972-38a5-438f-b543-cd9bb464f49a')
Don't need these

2020-07-30 13:08 UTC, NickGrantONS commented on config.py
> +    Config = TestConfig
Don't need this

2020-07-30 13:08 UTC, NickGrantONS commented on config.py
> +    DB_HOST_WRITE = os.getenv('DB_HOST_RW', 'localhost')
Don't need this

2020-07-30 13:08 UTC, NickGrantONS commented on config.py
> +    DB_PORT_WRITE = os.getenv('DB_PORT_RW', '6432')
Don't need this

2020-07-30 13:08 UTC, NickGrantONS commented on config.py
> +    DB_NAME_WRITE = os.getenv('DB_NAME_RW', 'postgres')
Don't need this

2020-07-30 13:09 UTC, NickGrantONS commented on config.py
> +    CASEAPI_PORT = os.getenv('CASEAPI_PORT', '8161')
Don't need these

2020-07-30 13:09 UTC, NickGrantONS commented on config.py
> +    ENVIRONMENT = os.getenv('ENVIRONMENT')
Don't need this

2020-07-30 13:10 UTC, NickGrantONS commented on utilities/rabbit_helper.py
> +def add_test_queue(binding_key, exchange_name, queue_name, exchange_type='topic'):
Don't need this

2020-07-30 13:11 UTC, NickGrantX requested changes
Lots of stuff that can be removed

2020-07-30 13:27 UTC, NickGrantX approved these changes

2020-07-31 06:16 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Split cloudshell utilities and monitoring tools out of census-rm-toolbox](https://trello.com/c/XHfzQUze/1257-split-cloudshell-utilities-and-monitoring-tools-out-of-census-rm-toolbox)

2020-07-31 08:50 UTC, ryangrundy7 approved these changes

2020-07-31 09:01 UTC, merged